---
name: build
on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    container: python:3.8-alpine
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint pytest
      
      - name: run linter
        run: pylint src

      - name: run python tests
        run: pytest tests/ -v